name: Build and publish Swagger

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "packages/swagger/**"

jobs:
  build_and_publish:
    uses: ./.github/workflows/publish.yml
    with:
      workspace: packages/swagger
      depends_on: packages/openapi
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
