name: Build and publish query

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "packages/query/**"

jobs:
  build_and_publish:
    uses: ./.github/workflows/publish.yml
    with:
      workspace: packages/query
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
