name: Build and publish rbac

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "packages/rbac/**"

jobs:
  build_and_publish:
    uses: ./.github/workflows/publish.yml
    with:
      workspace: packages/rbac
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
