name: Build and publish

on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
      depends_on:
        type: string
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm ci

      - run: npm test
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      - name: build dependencies
        if: ${{ !inputs.depends_on }}
        run: npm run build -w ${{ inputs.depends_on }}
      - run: npm run build -w ${{ inputs.workspace }}
      - run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
      - run: npm publish -w ${{ inputs.workspace }} --access public
